name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # Automatically run on every Sunday
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@3378cda945da322a8db4b193e19d46352ebe2de5 # ratchet:actions/create-github-app-token@v1.10.4
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # ratchet:actions/checkout@v4.1.7
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@64be81ba69383f81f2be476703ea6570c4c8686e # ratchet:saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull_request_branch: "github/actions-update"
          extra_workflow_locations: ".github/actions/build-base-image"
