name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    if: github.repository == 'erlang/otp'
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # ratchet:actions/create-github-app-token@v1.11.6
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # ratchet:actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/erlang/projects/13
          github-token: ${{ steps.generate_token.outputs.token }}
