name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    if: github.repository == 'erlang/otp'
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@9d97a4282b2c51a2f4f0465b9326399f53c890d4 # ratchet:actions/create-github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c # ratchet:actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/erlang/projects/13
          github-token: ${{ steps.generate_token.outputs.token }}
